name: mySQL-db

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${root_password}
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"
